before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: I3VZSzDNI/y6kXJrFJowfP1BvbC5cV0o6fgeZpScP+EH8KcAlEhGl1ggXZ6ZxCXnNjASVErTheio+RL9EPvOt1YU+6WzS4XMh9/kUTVYBtNnzHONuN5kYhVkJTWOybBKBcd8EHE4hmbyt+ISIz7PsrD5z90vt73dwVMi+i0wzTOsFPoUz8KzXHeIHwY3d57ecOuuluNdBILQJqb7yrCNJ6liQUvStRru5UHEYO+jGKSUC15w7oqAQl/jBCg6xWWzfiQc/HZz/My5NaJ8o3L24bXbBZf1xqV+AFfIXqkjfkqlPVW6uiyprfBPFm9p1krAPjDFDr3tK8Qa18F30jC/LD+ZApT9mRufWB9x/toeNeCOF34wllrrXfRg0Ca/4oSGXBxaahaN7NXXGL9TAX5VSL5oxE0ywzoQqb0BS0j1GyGPPJ+rmcPP7O5zygICE5p2TRQ3qFikR5ubb3J8i5ZwwEXE+48JGnLMWXlf3ncU4LfVw8Kxb5soSTpLXDKEsgwJ9zA233VkH6TPndt6MjHfoPURynaIbw1f1PpAYbRJ+tMvFfQds9N4jsliW7zxBdv6J9f7/QoMO/WPcM5/hUTb+ysCtvDDCQ0kZptgJVCxP1YhPMHTxOBrAdqzDkvfwGuE3lKQJyWmUJ/0hw6UDoMHk80eYMMPKkJvLE9f/ZuKZxg= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
